language: julia

os:
  - osx
  - linux
  - windows

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly

codecov: true
coveralls: true

notifications:
  email: false

branches:
  only:
  - master
  - devel

matrix:
    allow_failures:
        - julia: nightly

after_success:
  - julia -e 'import Pkg; cd(Pkg.dir("OpenQuantumSystems")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'import Pkg; cd(Pkg.dir("OpenQuantumSystems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
